apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
spec:
  type: website
  lifecycle: production
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  domain: ${{ values.domain }}
