apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-app-template
  title: React Application
  description: Cria um novo projeto React
  tags:
    - react
    - frontend
spec:
  owner: tribe-web-platforms
  type: website
  
  parameters:
    - title: Informações
      required:
        - component_id
        - description
        - owner
        - system
      properties:
        component_id:
          title: Nome
          type: string
          ui:field: EntityNamePicker
        description:
          title: Descrição
          type: string
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        system:
          title: Sistema
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System
    
    - title: Localização
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - bonett-labs

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
    
    - id: publish-code
      name: Publish Code
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main
        repoVisibility: private
    
    - id: fetch-metadata
      name: Prepare Metadata
      action: fetch:template
      input:
        url: ./metadata
        targetPath: ./metadata-output
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
    
    - id: publish-metadata
      name: Push Metadata
      action: publish:github
      input:
        repoUrl: github.com?repo=bonettech-zentry-components&owner=bonett-labs
        sourcePath: metadata-output
        defaultBranch: main
        gitCommitMessage: 'feat: Add ${{ parameters.component_id }} metadata'

  output:
    links:
      - title: Code Repository
        url: ${{ steps['publish-code'].output.remoteUrl }}
      - title: Metadata
        url: https://github.com/bonett-labs/bonettech-zentry-components/tree/main/${{ parameters.component_id }}
